auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("closed_listings", views.closed, name="closed"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("category_list", views.category_list, name="category_list"),
    path("categories/<str:category_name>", views.categories, name="categories"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("create_listing", views.create, name="create"),
    path("<int:listing_id>", views.listing, name="listing"),
    path("watchlisting/<int:listing_id>", views.opt_watchlist, name="watchlisting"),
    path("bidding/<int:listing_id>", views.bidding, name="bidding"),
    path("close/<int:listing_id>", views.close, name="close")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

class Categories(models.Model):
    name = models.CharField(max_length= 100, null=False)

    def __str__(self):
        return f"{self.name}"

class Listings(models.Model):
    title = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.CharField(max_length=400)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, related_name="categorized", default=1)
    image_url = models.CharField(max_length=300, blank=True)
    lister = models.ForeignKey(User, on_delete=models.CASCADE, related_name="listed_by", null=True)
    winner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="won", null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.title}"

class Bids(models.Model):
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bids", null=True)
    listing = models.ForeignKey(Listings, on_delete=models.CASCADE, related_name="bids_on", null=True)

    def __str__(self):
        return f"{self.amount}"

class Comments(models.Model):
    commenter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commented", null=True)
    comment = models.CharField(max_length= 500, null=False)
    listing = models.ForeignKey(Listings, on_delete=models.CASCADE, related_name="comments_on", null=True)

    def __str__(self):
        return f"{self.commenter}: {self.comment}"

class Watchlist(models.Model):
    listing = models.ForeignKey(Listings, on_delete=models.CASCADE, related_name="watchlisted", null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="watchlister", null=True)

    class Meta:
        unique_together = ('user', 'listing')

    def __str__(self):
        return f"{self.listing}"

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import User, Listings, Bids, Comments, Categories, Watchlist
from decimal import Decimal


def index(request):
    listings = Listings.objects.filter(active=True).order_by('-id')
    return render(request, "auctions/index.html", {
        "listings": listings
    })

def closed(request):
    listings = Listings.objects.filter(active=False).order_by('-id')
    return render(request, "auctions/closed.html", {
        "listings": listings
    })

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

def category_list(request):
   categories = Categories.objects.all()
   return render(request, "auctions/categories.html", {
        "categories": categories,
    })

def categories(request, category_name):
    category = get_object_or_404(Categories, name=category_name)
    listings = category.categorized.filter(active=True).order_by("-id")
    return render(request, "auctions/category.html", {
        "category": category,
        "listings" : listings
        })

@login_required
def create(request):
    if request.method=="POST":
        title = request.POST.get("title")
        if not title:
            return render(request, "auctions/error.html", {
                "message": "Please enter the name of the item to be listed."
            })

        description = request.POST.get("description")
        if not description:
            return render(request, "auctions/error.html", {
                "message": "Please enter the description of the item to be listed :("
            })

        price = request.POST.get("starting_bid")
        if not price:
            return render(request, "auctions/error.html", {
                "message": "Please enter the price (starting bid) of the item to be listed :("
            })

        category_id = request.POST.get("category_id")
        if not category_id:
            return render(request, "auctions/error.html", {
                "message": "Please choose a category for the item to be listed :("
            })

        category = Categories.objects.get(id=category_id)
        image_url = request.POST.get("image_url")

        lister = request.user

        listing = Listings(title=title, price=price, description=description, category=category, image_url=image_url, lister=lister)
        listing.save()
        return HttpResponseRedirect(reverse("auctions:listing", args=[listing.id]))
    return render(request, "auctions/create.html")


def listing(request, listing_id):
    listing = Listings.objects.get(pk=listing_id)
    if not listing:
        return render(request, "auctions/error.html", {
                "message": "Listing not found. :("
            })

    if request.method=="POST":

        # handling comments
        if not request.user.is_authenticated:
            return render(request, "auctions/error.html", {
                    "message": "Sign in or register to add new comments!"
                })
        comment = request.POST.get("comment")
        if not comment:
            return render(request, "auctions/error.html", {
                    "message": "Cannot add an empty comment :("
                })
        commenter = request.user

        comments = Comments(comment=comment, commenter = commenter, listing = listing)
        comments.save()

        return HttpResponseRedirect(reverse("auctions:listing", args=[listing.id]))

    highest_bid = Bids.objects.filter(listing = listing).order_by("-amount").first()
    in_watchlist = False
    if request.user.is_authenticated:
        in_watchlist = Watchlist.objects.filter(user=request.user, listing=listing).exists()
    return render(request, "auctions/listing.html", {
        "listing": listing,
        "comments": listing.comments_on.all().order_by('-id'),
        "in_watchlist": in_watchlist,
        "highest_bid" : highest_bid
    })

def opt_watchlist(request, listing_id):
    listing = Listings.objects.get(pk=listing_id)
    if not listing:
        return render(request, "auctions/error.html", {
                "message": "Listing not found. :("
            })
    if request.method=="POST":
        if not request.user.is_authenticated:
            return render(request, "auctions/error.html", {
                "message": "Sign in or register to add items to your watchlist. :)"
            })
        in_watchlist = Watchlist.objects.filter(user=request.user, listing=listing).exists()
        if not in_watchlist:
            add_to_watchlist = Watchlist(listing=listing, user=request.user)
            add_to_watchlist.save()
        else:
            Watchlist.objects.filter(user=request.user, listing=listing).delete()

    return HttpResponseRedirect(reverse("auctions:listing", args=[listing.id]))

@login_required
def watchlist(request):
   watchlisted = Watchlist.objects.filter(user=request.user).order_by('-id')
   listings = [watchlist.listing for watchlist in watchlisted]
   return render(request, "auctions/watchlist.html", {
        "watchlisted": watchlisted,
        "listings": listings
    })

def bidding(request, listing_id):
    listing = Listings.objects.get(pk=listing_id)
    if not listing:
        return render(request, "auctions/error.html", {
                "message": "Listing not found. :("
            })
    if request.method=="POST":
        if not request.user.is_authenticated:
            return render(request, "auctions/error.html", {
                "message": "Sign in or register to bid on items. :)"
            })
        bid = request.POST.get("bid")
        if not bid:
           return render(request, "auctions/error.html", {
                "message": "Please enter a valid amount to bid. :("
            })
        try:
            bid = Decimal(bid)
        except ValueError:
            return render(request, "auctions/error.html", {
                "message": "Please enter a positive integer to place your bid."
            })
        highest_bid = Bids.objects.filter(listing = listing).order_by("-amount").first()
        success_message = None
        if bid < 0:
            return render(request, "auctions/error.html", {
                "message": "Please enter a positive integer to place your bid."
            })

        if highest_bid is None and bid >= listing.price:
            bids = Bids(amount = bid, bidder = request.user, listing = listing)
            bids.save()
            success_message = "Your bid was placed successfully!"

        elif highest_bid is not None and bid > highest_bid.amount:
            bids = Bids(amount = bid, bidder = request.user, listing = listing)
            bids.save()
            success_message = "Your bid was placed successfully!"
            highest_bid = Bids.objects.filter(listing = listing).order_by("-amount").first()

        else:
            return render(request, "auctions/error.html", {
                "message": "Your bid must be at least as large as the starting bid, and must be greater than any other bids that have been placed."
            })

        in_watchlist = False
        if request.user.is_authenticated:
            in_watchlist = Watchlist.objects.filter(user=request.user, listing=listing).exists()

        return render(request, "auctions/listing.html", {
            "listing": listing,
            "in_watchlist" : in_watchlist,
            "success_message": success_message,
            "highest_bid": highest_bid
        })
    return HttpResponseRedirect(reverse("auctions:listing", args=[listing.id]))

def close(request, listing_id):
    listing = Listings.objects.get(pk=listing_id)
    if not listing:
        return render(request, "auctions/error.html", {
                "message": "Listing not found. :("
            })
    if request.method=="POST":
        close = request.POST.get("close")
        if not close:
            return render(request, "auctions/error.html", {
                "message": "Try closing the auction for the listing again. :("
            })
        if listing.lister == request.user:
            user = request.user
            listing.active = False
            listing.save()

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}
{% block title %}
   Auction: Categories
{% endblock %}

{% block body %}
<div style="color:#080811; font-size: 22px; font-weight:600; padding-left: 10px;" class="font-gen">CATEGORIES</div>
               {% for category in categories %}
               <div style="background-color: #303035; color:#dee2e6;">
                  <a href="{% url 'auctions:categories' category.name %}" style="text-decoration: none; color: inherit;">
                     <ul class="font-gen">
                        {{ category.name }}
                        <hr>
                     </ul>
                  </a>
               </div>
               {% endfor %}
{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}
{% block title %}
   Categories
{% endblock %}

{% block body %}

    <div style="color:#080811; font-size: 22px; font-weight:600; padding-left: 10px;" class="font-gen">In {{category.name}}</div>

    {% if listings %}
    {% for listing in listings %}
         <a href="{% url 'auctions:listing' listing.id %}" style="text-decoration: none;">
         <div class="card mb-3" style="max-width: 1700px; height: 300px; padding-top: 10px; margin-left: 10px; margin-top: 20px;">
            <div class="row g-0">
                  <div class="col-md-4">
                  {% if listing.image_url %}
                     <img src="{{listing.image_url}}" class="img-fluid rounded-start w-50" alt="{{listing.title}}" style="margin-left: 60px; margin-top: 5px;">
                  {% endif %}
                  </div>
                  <div class="col-md-7 font-gen" style="margin-top: 14px;">
                     <div class="card-body">
                        <h5 class="card-title" style="font-weight: 600; font-size: 30px;">{{listing.title}}</h5>
                        <p class="card-text"><strong>Description:</strong> {{listing.description}}</p>
                        <p class="card-text"><strong>Current Price:</strong> ${{listing.price}}</p>
                        <p class="card-text"><small class="text-body-secondary"><strong>Listed By:</strong> {{listing.lister.username}}</small></p>
                     </div>
                 </div>
             </div>
         </div>
         </a>
    {% endfor %}
    {% else %}
      <p style="padding-top: 20px; padding-left: 11px;" class="font-gen">No items are categorized under this title.</p>
      {% endif %}

{% endblock %}

auctions/templates/auctions/closed.html
{% extends "auctions/layout.html" %}
{% block title %}
    Auctions
{% endblock %}

{% block body %}
    <div style="color:#080811; font-size: 22px; font-weight:600; padding-left: 10px;" class="font-gen">CLOSED LISTINGS</div>

    {% for listing in listings %}
    <a href="{% url 'auctions:listing' listing.id %}" style="text-decoration: none;">
    <div class="card mb-3" style="max-width: 1700px; height: 300px; padding-top: 10px; margin-left: 10px; margin-top: 20px;">
        <div class="row g-0">
            <div class="col-md-4">
             {% if listing.image_url %}
                <img src="{{listing.image_url}}" class="img-fluid rounded-start w-50" alt="{{listing.title}}" style="margin-left: 60px; margin-top: 5px;">
             {% endif %}
            </div>
            <div class="col-md-7 font-gen" style="margin-top: 14px;">
                <div class="card-body">
                    <h5 class="card-title" style="font-weight: 600; font-size: 30px;">{{listing.title}}</h5>
                    <p class="card-text"><strong>Description:</strong> {{listing.description}}</p>
                    <p class="card-text"><strong>Listing Price:</strong> ${{listing.price}}</p>
                    <p class="card-text"><small class="text-body-secondary"><strong>Listed By:</strong> {{listing.lister.username}}</small></p>
                </div>
            </div>
        </div>
    </div>
    </a>
    {% endfor %}

{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}
{% block title %}
   Create Listing
{% endblock %}

{% block body %}

    <div style="color:#080811; font-size: 22px; font-weight:600; padding-left: 10px;" class="font-gen">CREATE LISTING</div>

     <form action = "{% url 'auctions:create' %}" method = "POST" style="padding-left: 10px; padding-top: 10px;" class="font-gen">
        <!--title, description, starting bid/original price, URL for the image(optional), category-->
        {% csrf_token %}
        <div class="mb-3">
          <label for="formGroupExampleInput2" class="form-label">Title (Required)</label>
          <input type="text" class="form-control" id="formGroupExampleInput2" name="title" placeholder="Enter title for the listing here">
        </div>

        <label for="floatingTextarea2">Description (Required)</label>
        <div class="form-floating" style="padding-top: 10px;">
          <textarea class="form-control" placeholder="Enter item description here" name="description" id="floatingTextarea2" style="height: 100px"></textarea>
          <label for="floatingTextarea2" style="color: #636363">Enter item description here</label>
        </div>

        <div class="mb-3" style="padding-top: 18px;">
        <label for="basic-url" class="form-label">Image URL to the item (Optional)</label>
        <div class="input-group">
            <span class="input-group-text" id="basic-addon3">https://image.com</span>
            <input type="text" class="form-control" id="basic-url" name="image_url" aria-describedby="basic-addon3 basic-addon4">
        </div>
        </div>

        <label for="formGroupExampleInput2" class="form-label">Category (Required)</label>
        <select class="form-select" aria-label="Default select example" name="category_id">
            <option selected style="background-color: #303035; color:#dee2e6;" disabled>Choose Category Here</option>
            <option value="2" style="background-color: #303035; color:#dee2e6;">Fashion</option>
            <option value="3" style="background-color: #303035; color:#dee2e6;">Stationeries</option>
            <option value="4" style="background-color: #303035; color:#dee2e6;">Toys</option>
            <option value="5" style="background-color: #303035; color:#dee2e6;">Electronics</option>
            <option value="6" style="background-color: #303035; color:#dee2e6;">Books</option>
        </select>

        <div class="mb-3" style="padding-top: 18px;">
          <label for="formGroupExampleInput2" class="form-label">Bidding starts at (Required)</label>
          <input type="text" class="form-control" id="formGroupExampleInput2" name="starting_bid" placeholder="Enter starting bid">
        </div>

        <button type="submit" class="btn btn-primary" style="background-color: #303035; color:#dee2e6; border: 0;">Save Listing</button>
        </form>
{% endblock %}

auctions/templates/auctions/error.html
{% extends "auctions/layout.html" %}
{% block title %}
    Error
{% endblock %}

{% block body %}
     <h1>Error</h1>
        <p>{{message}}</p>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% block title %}
    Auctions
{% endblock %}

{% block body %}
    <div style="color:#080811; font-size: 22px; font-weight:600; padding-left: 10px;" class="font-gen">ACTIVE LISTINGS</div>

    {% for listing in listings %}
    <a href="{% url 'auctions:listing' listing.id %}" style="text-decoration: none;">
    <div class="card mb-3" style="max-width: 1700px; height: 300px; padding-top: 10px; margin-left: 10px; margin-top: 20px;">
        <div class="row g-0">
            <div class="col-md-4">
             {% if listing.image_url %}
                <img src="{{listing.image_url}}" class="img-fluid rounded-start w-50" alt="{{listing.title}}" style="margin-left: 60px; margin-top: 5px;">
             {% endif %}
            </div>
            <div class="col-md-7 font-gen" style="margin-top: 14px;">
                <div class="card-body">
                    <h5 class="card-title" style="font-weight: 600; font-size: 30px;">{{listing.title}}</h5>
                    <p class="card-text"><strong>Description:</strong> {{listing.description}}</p>
                    <p class="card-text"><strong>Listing Price:</strong> ${{listing.price}}</p>
                    <p class="card-text"><small class="text-body-secondary"><strong>Listed By:</strong> {{listing.lister.username}}</small></p>
                </div>
            </div>
        </div>
    </div>
    </a>
    {% endfor %}

{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
      <nav class="navbar navbar-expand-md navbar" style="background-color: #303035;">
        <div class="container-fluid">
          <div style="color:#dee2e6; font-size: 18px; padding-top: 28px; padding-bottom: 25px; padding-left: 10px; font-weight:600;" class="font-gen">CS50W AUCTIONS</div>
            <div style="color:#a7a5b6; padding-right: 14px;">
                {% if user.is_authenticated %}
                    Signed in as <strong>{{ user.username }}</strong>.
                {% else %}
                    Not signed in.
                {% endif %}
            </div>
        </div>
     </nav>
        <ul class="nav navbar navbar-expand-md" style="background-color: #151520">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:closed' %}">Closed Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:category_list' %}">Categories</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:create' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}
{% block title %}
   Create Listing
{% endblock %}

{% block body %}
         {% if user == listing.winner %}
            <div class="alert alert-success" role="alert" style="margin-top: 10px; margin-left: 10px;">
               Success!! You have won this auction!
            </div>
         {% endif %}

     <div style="padding-left: 10px; position: absolute;" class="font-gen">
         {% if listing.image_url %}
            <img src="{{listing.image_url}}" class="rounded w-25 float-start me-4 mb-4" alt="{{listing.title}}">
         {% endif %}
            <div style="color:#080811; font-size: 30px; font-weight:600;" class="font-gen">{{listing.title}}</div>
            <div style="padding-top: 10px;"><strong>Description:</strong> {{listing.description}}</div>
            {% if not listing.active and listing.winner %}
               <div style="padding-top: 10px;"><strong>Winner of the auction:</strong> {{listing.winner.username}}</div>
            {% else %}
               <div style="padding-top: 10px;"><strong>Bidding starts at:</strong> ${{listing.price}}</div>
            {% endif %}
            <div style="padding-top: 10px;"><strong>Category:</strong> {{listing.category}}</div>
            <div style="padding-top: 10px;"><strong>Listed By:</strong> {{listing.lister.username}}</div>
     </div>

     {% if user == listing.lister %}
     <form action="{% url 'auctions:close' listing.id %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="close" value="close">
      {% if not listing.winner %}
       <button type="submit" class="btn btn-primary" style="background-color: #bc0000; color:#dee2e6; border: 0; margin-top: 6px; margin-left: 1330px; position: relative; width: 150px;">
         Close Auction
      </button>
      {% endif %}
     </form>
     {% endif %}

     <form action="{% url 'auctions:watchlisting' listing.id %}" method="post">
      {% csrf_token %}
       <button type="submit" name="watchlist" class="btn btn-primary" style="background-color: #303035; color:#dee2e6; border: 0; position: relative; margin-top: 240px; margin-left: 405px;">
         {% if not in_watchlist %}
         Add to Watchlist
         {% else %}
         Remove from Watchlist
      {% endif %}
      </button>
     </form>

   {% if listing.active %}
    <form action="{% url 'auctions:bidding' listing.id %}" method="post">
      {% csrf_token %}
         <div class="col-md-3" style="padding-left: 10px; padding-top: 150px; position: relative;">
            <label for="inputEmail4" class="form-label font-gen" style="font-size: 20px; font-weight: 500;"><strong>Bid on this item</strong></label>
            <input type="number" name="bid" class="form-control" style="font-size: 16px; border-color:#818181; height: 40px;" placeholder="Place your bid here in $">
            <div><small class="text-body-secondary font-gen"  style="font-size: 12px; padding-left: 2px;">Your bid must be at least as large as the starting bid.</small></div>
            <button type="submit" class="btn btn-primary" style="background-color: #303035; color:#dee2e6; border: 0; margin-top: 8px;">Place Bid</button>
            {% if success_message %}
               <div class="alert alert-success" role="alert" style="margin-top: 10px; padding-left: 10px;">
                  Your bid has been successfully placed!
               </div>
            {% endif %}
               <div style="padding-top: 10px;"><strong>Current Bid:</strong>
               {% if highest_bid %}
                  ${{highest_bid.amount}}
               {% else %}
                  No bids yet.
               {% endif %}
               </div>
         </div>
      </form>
      {% endif %}

     <form action="{% url 'auctions:listing' listing.id %}" method="post">
      {% csrf_token %}
         <div class="col-md-4"
         {% if not listing.active and listing.winner %}
            style="padding-top: 130px; padding-left: 10px; position: relative;"
         {% else %}
            style="padding-top: 30px; padding-left: 10px; position: relative;"
         {% endif %}>

            <label for="inputEmail4" class="form-label font-gen" style="font-size: 20px; font-weight: 500;"><strong>Comments</strong></label>
            <div class="d-flex gap-3">
               <input type="text" class="form-control" name="comment" placeholder="Add a new comment..." style="border-color:#818181;">
               <button type="submit" class="btn btn-primary" style="background-color: #303035; color:#dee2e6; border: 0;">Comment</button>
            </div>
         </div>
      </form>

      <div style="padding-top: 20px; padding-left: 11px; position: relative;" class="font-gen">
         {% if comments %}
            {% for comment in comments %}
               <div><strong>{{comment.commenter.username}}:</strong>  {{comment.comment}}</div>
               <hr>
            {% endfor %}
         {% else %}
            Be the first to comment.
         {% endif %}
      </div>

{% endblock %}>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block title %}
   Auctions: Login
{% endblock %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block title %}
   Auctions: Register
{% endblock %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}